from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yt_dlp

COOKIE_ATTR_NAMES = {
    "path",
    "domain",
    "expires",
    "max-age",
    "secure",
    "httponly",
    "samesite",
    "priority",
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert raw Douyin Cookie header into yt-dlp cookiefile and update .env.",
    )
    parser.add_argument("--cookie", help="Raw Cookie header string.")
    parser.add_argument(
        "--cookie-file",
        help="Path to a text file that contains raw Cookie header string (not Netscape cookiefile).",
    )
    parser.add_argument(
        "--output",
        default="tmp/douyin.cookies.txt",
        help="Output cookiefile path in Netscape format. Default: tmp/douyin.cookies.txt",
    )
    parser.add_argument(
        "--domain",
        default=".douyin.com",
        help="Cookie domain used in Netscape cookiefile. Default: .douyin.com",
    )
    parser.add_argument(
        "--env-file",
        default=".env",
        help="Path to .env file. Default: .env",
    )
    parser.add_argument(
        "--env-key",
        default="YTDLP_COOKIE_FILE",
        help="Environment variable key to upsert in .env. Default: YTDLP_COOKIE_FILE",
    )
    parser.add_argument(
        "--skip-env-update",
        action="store_true",
        help="Do not update .env file.",
    )
    parser.add_argument(
        "--encoding",
        default="utf-8",
        help="Encoding used when reading --cookie-file. Default: utf-8",
    )
    parser.add_argument(
        "--check-url",
        help="Optional URL to verify cookie freshness after writing cookiefile.",
    )
    parser.add_argument(
        "--check-timeout",
        type=int,
        default=20,
        help="Socket timeout seconds for --check-url. Default: 20",
    )
    return parser.parse_args()


def read_raw_cookie(args: argparse.Namespace) -> str:
    if args.cookie:
        raw = args.cookie
    elif args.cookie_file:
        raw = Path(args.cookie_file).read_text(encoding=args.encoding)
    else:
        print(
            "Paste raw Cookie string, then press Ctrl+Z and Enter (Windows) / Ctrl+D (Linux/macOS).",
            file=sys.stderr,
        )
        raw = sys.stdin.read()

    raw = raw.strip()
    if raw.startswith("# Netscape HTTP Cookie File"):
        raise ValueError(
            "Input looks like Netscape cookiefile, not raw Cookie header string. "
            "Please pass browser request Cookie header text."
        )
    if raw.lower().startswith("cookie:"):
        raw = raw.split(":", 1)[1].strip()
    return raw


def parse_cookie_pairs(raw_cookie: str) -> list[tuple[str, str]]:
    pairs: list[tuple[str, str]] = []
    index: dict[str, int] = {}

    normalized = raw_cookie.replace("\r", "\n").replace("\n", ";")
    for chunk in normalized.split(";"):
        part = chunk.strip()
        if not part or "=" not in part:
            continue

        name, value = part.split("=", 1)
        name = name.strip()
        value = value.strip()
        if not name:
            continue

        if name.lower() in COOKIE_ATTR_NAMES:
            # Ignore Set-Cookie attributes if they appear in pasted content.
            continue

        if name in index:
            pairs[index[name]] = (name, value)
        else:
            index[name] = len(pairs)
            pairs.append((name, value))

    return pairs


def write_netscape_cookie_file(output_path: Path, domain: str, pairs: list[tuple[str, str]]) -> None:
    include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
    secure = "TRUE"
    expiry = "2147483647"

    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by tools/setup_douyin_cookie.py",
    ]

    for name, value in pairs:
        safe_name = name.replace("\t", "").replace("\n", "")
        safe_value = value.replace("\t", " ").replace("\n", "")
        lines.append(
            "\t".join([domain, include_subdomains, "/", secure, expiry, safe_name, safe_value])
        )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.exists():
        backup_path = output_path.with_suffix(output_path.suffix + ".bak")
        backup_path.write_text(output_path.read_text(encoding="utf-8", errors="ignore"), encoding="utf-8")
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def upsert_env_value(env_file: Path, key: str, value: str) -> None:
    lines: list[str] = []
    if env_file.exists():
        lines = env_file.read_text(encoding="utf-8").splitlines()

    assign = f"{key}={value}"
    pattern = re.compile(rf"^\s*{re.escape(key)}\s*=")
    replaced = False
    updated: list[str] = []

    for line in lines:
        if pattern.match(line):
            updated.append(assign)
            replaced = True
        else:
            updated.append(line)

    if not replaced:
        if updated and updated[-1].strip():
            updated.append("")
        updated.append(assign)

    env_file.write_text("\n".join(updated) + "\n", encoding="utf-8")


def check_cookie_works(cookie_file: Path, check_url: str, timeout: int) -> tuple[bool, str]:
    opts = {
        "quiet": True,
        "no_warnings": True,
        "noplaylist": True,
        "socket_timeout": timeout,
        "cookiefile": str(cookie_file),
    }
    try:
        with yt_dlp.YoutubeDL(opts) as ydl:
            ydl.extract_info(check_url, download=False)
        return True, "Cookie check passed."
    except Exception as exc:
        return False, str(exc)


def main() -> int:
    args = parse_args()
    try:
        raw_cookie = read_raw_cookie(args)
    except ValueError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    if not raw_cookie:
        print("ERROR: Empty cookie input.", file=sys.stderr)
        return 1

    pairs = parse_cookie_pairs(raw_cookie)
    if not pairs:
        print("ERROR: No valid cookie key/value pairs found.", file=sys.stderr)
        return 1

    output_path = Path(args.output)
    write_netscape_cookie_file(output_path, args.domain, pairs)

    required_names = {"s_v_web_id", "ttwid"}
    cookie_names = {name for name, _ in pairs}
    missing = sorted(required_names - cookie_names)

    output_for_env = str(output_path).replace("\\", "/")
    if not args.skip_env_update:
        upsert_env_value(Path(args.env_file), args.env_key, output_for_env)

    print(f"Cookie pairs parsed: {len(pairs)}")
    print(f"Cookie file written: {output_path}")
    if missing:
        print(f"WARNING: Missing common Douyin cookies: {', '.join(missing)}")
    if args.skip_env_update:
        print("Skipped .env update.")
    else:
        print(f"Updated {args.env_key} in {args.env_file}: {output_for_env}")

    if args.check_url:
        ok, message = check_cookie_works(output_path, args.check_url, args.check_timeout)
        if ok:
            print(f"Check URL OK: {args.check_url}")
        else:
            print(f"Check URL FAILED: {args.check_url}")
            print(message)
            return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
